name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Oracle VM via SSH
        uses: appleboy/ssh-action@9b978f09f2587beff9c80449f57cb0f0612d3039
        with:
          host: 140.238.251.248
          username: opc
          key: ${{ secrets.ORACLE_VM_SSH_KEY }}
          script: |
            cd /home/opc/gift
            git pull origin main
            pip install -r requirements.txt
            sudo systemctl restart gift-api.service
